### ISSUE TITLE
Python panel enter on Windows doesn't default to correct new lines

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#138]
### Issue

This is likely a Windows issue - but testing 0.8.1 I noticed that the Python panel often gave syntax errors:

![image](https://github.com/ggarra13/mrv2/assets/2439881/bda4acc9-99f3-40db-a412-1184c45782d7)

My entry in the script field:
```python

import mrv2
from mrv2 import annotations, cmd, math, image, io, media
from mrv2 import playlist, timeline, usd, settings

print(0)
print(1)
```

Would execute as:
```python
import mrv2
from mrv2 import annotations, cmd, math, image, io, media
from mrv2 import playlist, timeline, usd, settings

print(0)print(1)
```
Giving:
```
SyntaxError: invalid syntax (<string>, line 7)
```

It seems that the Enter key maybe does not generate the new lines as it expects (maybe `\r` instead of `\n`?)

My keyboard locale settings on Windows 10 are set to:
![image](https://github.com/ggarra13/mrv2/assets/2439881/9a8046eb-a70a-45a3-b5d1-6f299fe39159)

**Comment by BigRoy** [comment]
> [This version also addresses your Python Editor issues.](https://github.com/ggarra13/mrv2/issues/137#issuecomment-1766876818)

Just cross-referencing the comment from another issue. Should be fixed in 0.8.1 beta.

**Comment by BigRoy** [comment]
Fixed in 0.8.2 beta.

**Comment by BigRoy** [comment]
Note a huge issue but I do believe it's new behavior - whenever the command you run does not end with an empty new line the return value gets printed in the top report view on the same line. Like this:

![image](https://github.com/ggarra13/mrv2/assets/2439881/d6669ba4-83d3-4ac2-92ec-1eb4255606b5)

Note how the returned list appears directly after the `image.ocioIcsList()`.

It would be nicer if it'd appear like this:

![image](https://github.com/ggarra13/mrv2/assets/2439881/8bc8b33c-01c3-46e4-bd6c-8e0bd8506054)

In this case I just added a `#` line since that was the only thing that worked to get the return value onto a new line.
Would be great if the output could always report `"\n".join([command, result])` especially because you seem to already perform a `command.strip()` or alike on the input since any empty new lines already appear removed.

**Comment by ggarra13** [comment]
I have fixed that and updated the beta of v0.8.2 on all platforms and put it on sourceforge, on the beta folder (that way it is easier for people to find it instead of looking through the mrv2 issues).  Anyway, look for it in:

https://sourceforge.net/projects/mrv2/files/beta/

These are full releases not nightly builds, so they are compatible with RH 8.1 and have USD support on Windows.

**Comment by BigRoy** [comment]
Can confirm it's fixed in latest beta of v0.8.2

![image](https://github.com/ggarra13/mrv2/assets/2439881/9743ead8-efb7-429b-8883-775ba0856957)

**Comment by BigRoy** [comment]
Actually there seems to be another issue. It fails to close brackets over multiple lines in some cases, e.g. this fails:
```python

import mrv2
from mrv2 import annotations, cmd, math, image, io, media
from mrv2 import playlist, timeline, usd, settings

image_options = image.ImageOptions(
  videoLevels=image.InputVideoLevels.FromFile,
  alphaBlend=image.AlphaBlend.None,
  imageFilters=image.ImageFilters(
      minify=image.ImageFilter.Linear,
      magnify=image.ImageFilter.Linear
  )
)
```

With the simplest reproducable of the issue being:
```python
image_options = image.ImageOptions(
)
```

Whereas this works:
```python
image_options = image.ImageOptions()
```

**Comment by ggarra13** [comment]
What error do you get (and what Input does it print in the Python Display Window)?  Also, what happens if you select the section from the beginning of the assignment to the end of the parenthesis?

**Comment by BigRoy** [comment]
It seems to strip off the end parentheses:
```
SyntaxError: '(' was never closed (<string>, line 7)
```
Note the code that it runs:
![image](https://github.com/ggarra13/mrv2/assets/2439881/f80c0fa8-1380-4752-aada-1c4060b12a5d)

This does work:
```python

import mrv2
from mrv2 import annotations, cmd, math, image, io, media
from mrv2 import playlist, timeline, usd, settings

image_options = image.ImageOptions(
  # 
)
```
Or if I add a statement after it also works:
```python

import mrv2
from mrv2 import annotations, cmd, math, image, io, media
from mrv2 import playlist, timeline, usd, settings

image_options = image.ImageOptions(
)
print("A")
```

**Comment by ggarra13** [comment]
This one I'll leave it to investigate it tomorrow.

**Comment by BigRoy** [comment]
> [Python Editor fixes (hopefully, there are no more errors, but let me know if there are still things broken).](https://github.com/ggarra13/mrv2/issues/143#issuecomment-1771307261)

Latest beta still produces this error for me:
![image](https://github.com/ggarra13/mrv2/assets/2439881/ac836ef6-3cbd-4904-b55f-1919445a09b6)

**Comment by ggarra13** [comment]
There's still an issue left.  If you do:

cmd.ImageOptions( keyword = var )

without a variable at the beginning like:

o = cmd.imageOptions( keyword = var )

You will still get a syntax error.

**Comment by ggarra13** [comment]
I fixed that final issue too.  Latest beta on sourceforge.

**Comment by BigRoy** [comment]
Unfortunately the new line issue still exists. In Python this should technically work:

```python
image.ImageFilters(minify=image.ImageFilter.Nearest
)
```
But it fails in latest beta. This is what it shows in the report:
```
import mrv2
from mrv2 import annotations, cmd, math, image, io, media
from mrv2 import playlist, timeline, usd, session, settings

image.ImageFilters(minify=image.ImageFilter.Nearest)
image.ImageFilters(minify
SyntaxError: '(' was never closed (<string>, line 2)
```
It seems to duplicate the last line, including a split off one?

This fails the same way:
```python

import mrv2
from mrv2 import annotations, cmd, math, image, io, media
from mrv2 import playlist, timeline, usd, session, settings

image.ImageFilters(
    minify=image.ImageFilter.Nearest,
    magnify=image.ImageFilter.Nearest
)
```

But this works:

```python
import mrv2
from mrv2 import annotations, cmd, math, image, io, media
from mrv2 import playlist, timeline, usd, session, settings

image.ImageFilters(
    minify=image.ImageFilter.Nearest,
    magnify=image.ImageFilter.Nearest)
```

![image](https://github.com/ggarra13/mrv2/assets/2439881/c6ce82a3-b31c-43da-9cec-664e80b112fe)

**Comment by ggarra13** [comment]
New beta on sourceforge.  I am betting that this time it will all work.  I cleaned up the code and documented the algorithm.

**Comment by BigRoy** [comment]
That does seem to work now - the only thing I can't seem to get to work is to set the video levels in this call:
```python
image_options = image.ImageOptions(
  videoLevels=image.InputVideoLevels.FromFile,
  alphaBlend=image.AlphaBlend.kNone,
  imageFilters=image.ImageFilters(
      minify=image.ImageFilter.Linear,
      magnify=image.ImageFilter.Linear
  )
)
```
Results in:
```
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. mrv2.image.ImageOptions()
    2. mrv2.image.ImageOptions(videoLevels: mrv2.image.InputVideoLevels, alphaBlend: mrv2.image.AlphaBlend, imageFilter: mrv2.image.ImageFilters)

Invoked with: kwargs: videoLevels=<InputVideoLevels.FromFile: 0>, alphaBlend=<AlphaBlend.kNone: 0>, imageFilters=<mrv2.image.ImageFilters minify=Linear magnify=Linear>

At:
  <string>(10): <module>
```

This works though:
```python
video_levels = image.InputVideoLevels(0)

image_options = image.ImageOptions(
  videoLevels=video_levels,
  alphaBlend=image.AlphaBlend.kNone,
  imageFilters=image.ImageFilters(
      minify=image.ImageFilter.Linear,
      magnify=image.ImageFilter.Linear
  )
)
```

But the constructor for InputVideoLevels still seems off. It also feels weird it needs it own constructor since it only takes one value?

**Comment by ggarra13** [comment]
Try this.  It is imageFilter not imageFilters.  This works for me:

image_options = image.ImageOptions(
  videoLevels=image.InputVideoLevels.FromFile,
  alphaBlend=image.AlphaBlend.kNone,
  imageFilter=image.ImageFilters(
      minify=image.ImageFilter.Linear,
      magnify=image.ImageFilter.Linear
  )
)

**Comment by ggarra13** [comment]
Oh. Wait. It was a typo on my part in the constructor parameters.  I'll fix it.

**Comment by ggarra13** [comment]
Yes, it is a typo on my part.  I'll have a fix in 30 mins the beta sourceforge site.

**Comment by ggarra13** [comment]
Can I close this issue?
