### ISSUE TITLE
Timeline Glitches

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#285]
When i grab this handle thing to reveal the timeline thumbnails, i can only drag it into one direction. To move it back down, i have to release the mouse, and grab it again.

https://github.com/user-attachments/assets/819adad1-7998-447a-8a36-be3f61ce4f03

I also noticed that the thumbnail view sometimes glitches completely, when i close the timeline, resize the window, and open the timeline again.
![image](https://github.com/user-attachments/assets/1448f281-f91f-41a1-990f-b043691f3f5b)

**Comment by ggarra13** [comment]
First problem of dragging timeline is now fixed in v1.2.4 beta (on sourceforge).

> I also noticed that the thumbnail view sometimes glitches completely, when i close the timeline, resize the window, and open the timeline again.

Can you provide step by step instructions on how to reproduce this?

**Comment by Thane5** [comment]
I downloaded the latest beta from sourceforge, but the draggins issue still is there.


Here is the simplest way to reproduce the display glitch:
1. Open a file
2. resize the window to half its size
3. drag the timeline open

**Comment by ggarra13** [comment]
> I downloaded the latest beta from sourceforge, but the draggins issue still is there.
>

Sorry.  I did not upload it to sourceforge as I had turned off the automatic uploading.  Here's the v1.2.4 betas:

.exe:
https://mega.nz/file/7aYiEKDY#rXklenQSoH0DDStIRhjap3tkLmpf1py41lGUdYpA-PA

.zip:
https://mega.nz/file/PbAjHLZT#OtwUMeEZQNPgwDLwOPLPlrqBYpAO--y0QXXt3qbAYng
 
> Here is the simplest way to reproduce the display glitch:
> 
> 1. Open a file
> 2. resize the window to half its size
> 3. drag the timeline open

I'm afraid I cannot reproduce it.  Can you provide more info:

1. Open a file.  --  Movie, Sequence or Single Frame?  Image Size?  Can you provide a pic or movie file that makes it fail?
2. Tried that.
3. Seems to work for me.  -- Do you also get a glitch if after resizing, you click on the Edit button?

**Comment by ggarra13** [comment]
I added some questions to the original request.

**Comment by Thane5** [comment]
Ah, that was easy. Now that i have the real beta, both bugs are gone.
